### ISSUE TITLE
Instagram account banned

### ISSUE THREAD

**Issue by dfsssssssgg** [AssetKid/raider-release#106]
So, the dev has been offline for 18 months.
Instagram seems to have caught up and my account has been displaying a message:

Try again later
We limit how often you can do certain things on Instagram to protect our community. Tell us if you think we made a mistake.

Please come back and fix or pass the project on to other ppl. We need this app. I've donated before to thank the devs but now it seems like this is all for nothing?

Thanks

**Comment by KaunWho** [comment]
I wish the code was open source so someone could've removed the kinks and forked a version. Its sad that this is going to die soon. Was a good option.

**Comment by AssetKid** [comment]
> We limit how often you can do certain things on Instagram to protect our community. Tell us if you think we made a mistake.

Your account is not banned, just temporarily action blocked.

It is hard to say if Raider caused this. **Mass** following/unfollowing, liking & commenting can cause this issue.

This happens often even to non-Raider users.

- https://www.reddit.com/r/Instagram/comments/kz8530/we_limit_how_many_times_you_can_do_certain_things/
- https://www.quora.com/What-does-it-mean-when-Instagram-says-we-limit-how-we-do-things-to-protect-our-community

Kindly keep your useragent up-to date and avoid using your Instagram account (on app or web) while Raider is running.

Instagram cracks down heavily on bot activity and spammers. Using the same account on two different devices concurrently raises some red flags.

Closing this for now.
