### ISSUE TITLE
Raider stops downloading when entering Settings menu[BUG]

### ISSUE THREAD

**Issue by avekifes** [AssetKid/raider-release#11]
Raider will stop downloading if I enter the Settings menu during a mass update. I'm not sure what the exact trigger is, but it seems to happen if I hit the System tab, or go from the System tab to the General tab in the middle of a download. 

There was an odd instance where Raider began downloading again when I started scrolling through the options on the General tab. This bug may affect single downloads as well, but I haven't tested it.

**Comment by AssetKid** [comment]
Fixed in [`v1.4.0`](https://github.com/AssetKid/raider-release/releases/tag/v1.4.0)
