### ISSUE TITLE
Import usernames from registered accounts

### ISSUE THREAD

**Issue by eldark** [AssetKid/raider-release#12]
It would be nice to have the option to import the accounts (left menu, Accounts) I wish to monitor directly from the "following" list in the stored accounts (the ones from Settings / General / Accounts).

**Comment by AssetKid** [comment]
Not feasible at the moment. The `following` API endpoint does get rate limited. If you follow a lot of accounts, it won't be possible to fetch them all.

**Comment by eldark** [comment]
And what about providing a list of usernames (text file, etc) and mass-import them?

**Comment by AssetKid** [comment]
https://github.com/AssetKid/raider-release/issues/3#issuecomment-526864700

**Comment by eldark** [comment]
Right. Didn't see it. Will try that!
