### ISSUE TITLE
import without having to enter name of folder

### ISSUE THREAD

**Issue by beakwood** [AssetKid/raider-release#14]
I've been able to convert csv file to json with the userid's username, timestamps, and names. But, I cannot get it to automatically default to the username or name for the folder to be created. As I want to be able to hit update all button without having to manually press or click the OK to default to using the username. There was something I did without having to put in the name of the folder and it did default to using the username instead. But I can't remember how I did it though it was to do with the acc.json. Over 300 names and having to manually press okay is quite a lengthy process. Overall, I do enjoy the fact that I'm not getting any of those 403 errors etcs.

**Comment by AssetKid** [comment]
How to import accounts - https://github.com/AssetKid/raider-release/issues/3#issuecomment-526864700

**Comment by KaunWho** [comment]
@beakwood were you updates accounts post updating the 'acc' file?
