### ISSUE TITLE
[BUG] Rate Limit with large subscriptions. 

### ISSUE THREAD

**Issue by beakwood** [AssetKid/raider-release#15]
I found that you can "update all" if you have no more than 70 subscriptions. Anything more than 70 subs, will result in a rate limit (and who knows when it is lifted, 24hrs?). As troublesome as it is, I've been going into the acc file and putting in my 70 subs manually and then clicking the update all button. So I'm curious if this is a bug, as I have my  "download timeout" set to 300 seconds to not hit the rate limit. But it will still happen if I have over 70 subs. I also have at default the mass update max post set at 50.  Is there a way to have this implemented or a possibility of being able to do this in the options to not hit the limit and set it to do 70 subs at a time or something?

**Comment by AssetKid** [comment]
This is not a bug. Instagram does rate limit their API. The limit goes down substantially if you actively use the Instagram app/site.

In my experience, the limit is usually lifted after a few minutes (I do not actively use Instagram)

Someone proposed a cool down timer between accounts which might help with the rate limit.

You can follow the progress from here #9

**Comment by beakwood** [comment]
> 
> 
> This is not a bug. Instagram does rate limit their API. The limit goes down substantially if you actively use the Instagram app/site or other downloaders.
> 
> In my experience, the limit is usually lifted after a few minutes (I do not actively use Instagram)
> 
> Someone proposed a cool down timer between accounts which might help with the rate limit.
> 
> You can follow the progress from here #9

That's the problem. For some reason, it's not obeying my "300 seconds" interval. And it's downloading the next profile immediately. I'm using 1.4.0.

with 200 profiles it hits the rate limit with the "300 seconds".

**Comment by AssetKid** [comment]
Download timeout is something different.

`If the request takes longer than 'timeout' amount, the request will be aborted.`
