### ISSUE TITLE
[BUG]"Mass Update Max Posts" value not being respected

### ISSUE THREAD

**Issue by avekifes** [AssetKid/raider-release#17]
Raider is downloading far more items than the value entered for "Mass Update Max Posts." I have mine set at 30 and ended up with over 100 files for some accounts.

**Comment by AssetKid** [comment]
Does the account in question have many slideshow posts?

A single post can have 10 files.

`Max Posts` limits the number of posts, not files.

**Comment by avekifes** [comment]
Yep, that would explain it.

**Comment by avekifes** [comment]
I forgot to ask: are story and highlight circles considered single posts as well, despite having multiple files?

**Comment by AssetKid** [comment]
> I forgot to ask: are story and highlight circles considered single posts as well, despite having multiple files?

No. The `Max Posts` setting only applies to the user's feed media.
