### ISSUE TITLE
Strange quirks

### ISSUE THREAD

**Issue by avekifes** [AssetKid/raider-release#2]
I'm using the portable version, if that matters.

When I enter my log-in information, Raider takes me to my feed, but my account isn't actually added. It's only after I restart the app that it shows up. Removing an account also requires a restart.

I also noticed that the "X" button next to Settings stopped working after I tried removing an account.

**Comment by AssetKid** [comment]
This should be fixed in the next release.

**Comment by AssetKid** [comment]
This should be fixed in `v1.0.5`
