### ISSUE TITLE
Support for IGTV videos

### ISSUE THREAD

**Issue by saajo-lab** [AssetKid/raider-release#23]
Support for IGTV videos could be a nice new feature for the program. Thank you.

**Comment by AssetKid** [comment]
From the few accounts I have checked, it seems IGTV videos do appear on the main feed and thus are downloaded by Raider. Only IGTV videos uploaded before 2019 seem to be missing on the main feed.

If that is the case, there are quite a number of apps & addons that you can use to fetch the older videos. Raider will continue fetching the new ones.
