### ISSUE TITLE
[BUG] The update fails when the account has over 10k files.

### ISSUE THREAD

**Issue by KaunWho** [AssetKid/raider-release#26]
When setting the accounts on auto update, if one of the account has more than 10k files, the auto update fails and you are rate limited. Since the in-built feature updates the account that was not updated since a longer period, it always starts with the same account due to which the update failed.

In my case the account in question was downloaded individually and the bulk of the posts were downloaded. However, while updating the posts it fails.

Fix I can suggest. Rather than getting the data of all the posts and checking which all were downloaded, if there's a way to check for posts only since the last update, then this could be avoided.

If there's a log file that you'll need, let me know where to find that. Will provide the details.

**Comment by AssetKid** [comment]
I am not sure I follow.

During auto update, only a maximum of 200 posts (`Mass Update Max Posts` setting) can be fetched. The account might have 10k posts but auto update will use the number you set in `Mass Update Max Posts`.
