### ISSUE TITLE
Sort by last updated

### ISSUE THREAD

**Issue by KaunWho** [AssetKid/raider-release#27]
Hey!
In the Account menu, we have 3 sorting options : Name, Newest and Oldest.
I was hoping if you could combine newest and oldest under 'Date Added' and provide an option to sort via 'Last Updated'.

Thanks and Regards
KW

**Comment by AssetKid** [comment]
Hey,

The `newest` and `oldest` options track the updated time, not the date added.

* `Newest` - Most recent updated account appears first

* `Oldest` - Most recent updated account appears last

**Comment by KaunWho** [comment]
Oh I must not have noticed that! thanks!
