### ISSUE TITLE
Error: Unable to save file to disk

### ISSUE THREAD

**Issue by KaunWho** [AssetKid/raider-release#28]
I'm receiving an error which states that 'Unable to save to disk. Ensure you have enough space then try again'. The system has lot of available free space. When I click on ok and try to download again, the download is successful.

**Comment by KaunWho** [comment]
![image](https://user-images.githubusercontent.com/58679929/72519483-713b4a80-387d-11ea-9c27-529ec861fd20.png)

**Comment by AssetKid** [comment]
Hey,

Check if the error message was logged.

To open the log dialog, move your mouse to the bottom right side of the window and click the bug icon that appears.

![image](https://user-images.githubusercontent.com/40426812/72526823-53b7b200-3878-11ea-86a4-555355241464.png)

**Comment by KaunWho** [comment]
This is what it has:

![image](https://user-images.githubusercontent.com/58679929/72633456-821fb500-397e-11ea-87ca-897af678888e.png)

**Comment by KaunWho** [comment]
Here you go:
![image](https://user-images.githubusercontent.com/58679929/72633575-c612ba00-397e-11ea-85ee-9344aa097180.png)

**Comment by AssetKid** [comment]
Hey,

Go to the shown location and manually rename the `prefs.765998691` file to `prefs`. I will investigate further what is causing this issue.

**Comment by AssetKid** [comment]
This should, hopefully, be fixed in `v1.5.3`.
