### ISSUE TITLE
New feature suggestions

### ISSUE THREAD

**Issue by avekifes** [AssetKid/raider-release#3]
Nice job on the app. Here are the first things I would add if I had your talent:

1. Add a way to import all accounts that a user is following/subscribed to.

2. Refine the "update all" function so Raider cycles through all subscribed accounts indefinitely (so no Stories are missed), but have it update only one account at a time (with a short interval between each) so rate limiting isn't triggered.

3. Custom filename options (e.g., add timestamp).

4. Add a way to download content that was only posted after/before/during a certain period.

**Comment by AssetKid** [comment]
> Add a way to import all accounts that a user is following/subscribed to.

Not possible. If you are following a couple thousand accounts, the API will be rate limited before all accounts are fetched.

You can test this on your browser.

> Refine the "update all" function so Raider cycles through all subscribed accounts indefinitely (so no Stories are missed), but have it update only one account at a time (with a short interval between each) so rate limiting isn't triggered.

I am looking for a way to have the application run in the system tray and auto-update all accounts every x hours.

Running the 'Update All' function indefinitely does not seem feasible.

> Custom filename options (e.g., add timestamp)

The first part of the filename is a [Unix timestamp](https://en.wikipedia.org/wiki/Unix_time). You can write a small script that extracts that part and converts it to your desired output.

Unix timestamps are universal and there is no plan to change this for now.

> Add a way to download content that was only posted after/before/during a certain period.

I will look into this.

**Comment by avekifes** [comment]
> Not possible. If you are following a couple thousand accounts, the API will be rate limited before all accounts are fetched.

Can this be done by importing a file (e.g., .txt) with a list of accounts?

**Comment by AssetKid** [comment]
> Can this be done by importing a file (e.g., .txt) with a list of accounts?

This is possible but it sounds like a very niche feature. If you want to import a large number of accounts, just edit the `acc` file in the save directory.

It is just a simple JSON file. You can easily add new entries to the file using the format below (Do not include the comments).

```js
  {
    "name": "Dogs", // Save Folder Name
    "username": "dogs", // Instagram Username
    "pendingRefresh": true // Tells the app that it should fetch & save the user ID
  }
```

That is it. The account will now show up on the list of subscribed accounts.

### *BACKUP THE `acc` FILE BEFORE PROCEEDING*

**Comment by avekifes** [comment]
I figured out how to import my subscriptions by converting a CSV to JSON, but is the current "update all" function safe to use if I have a lot of accounts? Raider seems to process one account at a time, so I shouldn't be rate limited, right?

Also, how does the "Mass Update Max Posts" work? If I set it to 200, does that mean Raider will download a maximum of 200 files per account, or will the program stop completely after downloading 200 files?

**Comment by AssetKid** [comment]
A single profile page query returns 50 posts. The stories query returns 100 entries.

If you set `Mass Update Max Posts` to 200 and also fetch stories, those will be 5 total API queries. If you have a lot of accounts, maybe reduce the `Mass Update Max Posts` to 50 or 100.

In the next update, the 'Update All' function will start with accounts that have not been updated in a while.

**Comment by avekifes** [comment]
I got rate limited after 333 profiles (out of a total of 1324) with Stories only and Max Update Max Posts set to 50. Most of the accounts didn't even have Stories to download.

Do you think an option for setting an interval between each account would help? (I'm assuming that hundreds of queries one right after another is what set it off.)

**Comment by AssetKid** [comment]
Are you logged in? The limit tends to be higher if you are logged in.

**Comment by avekifes** [comment]
I am. I thought you had to be logged in to download Stories.

**Comment by AssetKid** [comment]
Ok. I will stress test it and see what can be changed/improved.

**Comment by AssetKid** [comment]
>Custom filename options (e.g., add timestamp).

This is has been added in `v1.1.0`
---

I am closing this issue for now. Kindly open separate issues for requests 2 & 4 so that I can track them easily.

You can also file a new bug report for the rate limit issue if it is still hapeening.

**Comment by KaunWho** [comment]
> Nice job on the app. Here are the first things I would add if I had your talent:
> 
> 1. Add a way to import all accounts that a user is following/subscribed to.
> 2. Refine the "update all" function so Raider cycles through all subscribed accounts indefinitely (so no Stories are missed), but have it update only one account at a time (with a short interval between each) so rate limiting isn't triggered.
> 3. Custom filename options (e.g., add timestamp).
> 4. Add a way to download content that was only posted after/before/during a certain period.

Are you aware of any method to get the list of accounts that I follow into a txt/csv file? I used Helper tools on chrome, but that has stopped working.
