### ISSUE TITLE
[BUG] option to download the stories is always grayed out

### ISSUE THREAD

**Issue by danmirage** [AssetKid/raider-release#31]
A friend is posting dance-instruction practice "Live Video" in Stories.
We tried to download but, though he has stories, Raider did not provide the option to download the stories. The option to download the stories is always grayed out.
Does Raider recognize recorded live stories?

**Comment by AssetKid** [comment]
> **Live videos**

Raider uses the Instagram Web API. Unfortunately, live videos are not yet supported on the web version.

> **Stories button grayed out**

You need to add an account to view & download stories & highlights.

![image](https://user-images.githubusercontent.com/40426812/77778347-ed15f800-7061-11ea-8200-6384d72d7951.png)

**Comment by danmirage** [comment]
Thank you! Got it! 
Sorry, I did not understand the functionality!
