### ISSUE TITLE
Update All button on the homescreen

### ISSUE THREAD

**Issue by KaunWho** [AssetKid/raider-release#33]
Hey!

Is it possible to have an update all button on the home screen rather than opening the drawer menu from the left. Opening the drawer is a laggy experience, if you could also work to get that transition smoother, it would be wonderful.

Thanks!

**Comment by AssetKid** [comment]
There is an `Update Accounts` option on the system tray menu.

![image](https://user-images.githubusercontent.com/40426812/77947233-4b461380-72cc-11ea-9962-e1f5f6bedd2c.png)

You can enable the tray icon from settings.
