### ISSUE TITLE
live broadcast capture

### ISSUE THREAD

**Issue by sudo-do** [AssetKid/raider-release#36]
I know this is kind of weird and hard but i want something like this:
check is there any live every x minutes, if there's capture it. when live is finished save it to /account/lives/

Instagram sends notifies to mobile devices about new lives from followed accounts, maybe there's a api for it for PC?

**Comment by AssetKid** [comment]
Hey,

Capturing livestreams is currently out of scope. I have added the `future-proposal` label and will revisit this in the future.

Closing for now.
