### ISSUE TITLE
[BUG] Update all after editing the 'acc' file breaks the process

### ISSUE THREAD

**Issue by KaunWho** [AssetKid/raider-release#37]
I updated the acc json file as it was mentioned in the previous issues. I had 500+ accounts already in the acc file, added more into it and restarted Raider. When updating all, it didnt follow the rule of updating the account which wasn't updated recently.
 I let 100+ accounts to update and then closed and restarted the app.
This time it again started updating all the accounts. It updated all the accounts that were previously updated rather then updating the Pending Refresh ones. Is there a way around or am I missing something?

**Comment by AssetKid** [comment]
You can set the `updated` key (in the accounts JSON file) to 1 for the accounts you added manually.

**Comment by KaunWho** [comment]
This worked like a charm. Closing the issue. Thanks buddy!
