### ISSUE TITLE
Highlights download not working for accounts with many highlight reels

### ISSUE THREAD

**Issue by filipivc** [AssetKid/raider-release#4]
Just allow download all highlits from instagram.

**Comment by AssetKid** [comment]
Highlights download support added in [`v1.3.0`](https://github.com/AssetKid/raider-release/releases/tag/v1.3.0)

**Comment by filipivc** [comment]
tested today, not working on Raider.Portable.1.3.0.

**Comment by filipivc** [comment]
> Highlights download support added in [`v1.3.0`](https://github.com/AssetKid/raider-release/releases/tag/v1.3.0)

tested today, not working on Raider.Portable.1.3.0. highlights folder created but still empty.

**Comment by AssetKid** [comment]
Just tested it out and everything seems to be working just fine on my side.

Kindly ensure you have selected the `highlights` option & the profile has posted highlights to their feed.

**Comment by filipivc** [comment]
I'm pretty sure. Can you test on profile name: @tioricco ?

**Comment by AssetKid** [comment]
On your browser, are you able to view the highlights for that profile? I have tried using 2 accounts and they are not loading.

![image](https://user-images.githubusercontent.com/40426812/66617282-2aceb380-ebdd-11e9-8388-46c429c38edd.png)

It only works in the app.

**Comment by filipivc** [comment]
yes, working on web with 2 different logins. try this url https://www.instagram.com/stories/highlights/17976582835262673/

**Comment by AssetKid** [comment]
This should now be fixed in [`v1.4.0`](https://github.com/AssetKid/raider-release/releases/tag/v1.4.0)

**Comment by filipivc** [comment]
Working, thanks.
