### ISSUE TITLE
Skipping Errors

### ISSUE THREAD

**Issue by supersick123** [AssetKid/raider-release#41]
This is building on #40, but I've made a separate thread since it's also a distinct request.

It would be nice if Raider simply skipped any profiles that encounter errors (such as, but not limited to, #39), mark them as failed, then move on to the next profile. This avoid the need to continually check the program to make sure it didn't abruptly stop because it encountered an issue, which would delay the updates of other profiles if it isn't acknowledged. Ideally, a user would be able to let the program run in its entire course and then read the log/report at the very end as a "final check" to see if anything was missed.

**Comment by supersick123** [comment]
Ignore the request for an error report. Answered in #34.

**Comment by AssetKid** [comment]
This is the default behavior. If an account download fails, it should move to the next one in the queue.

Closing this in favor of #39
