### ISSUE TITLE
[BUG] Removing an account deletes the last login, not the account selected

### ISSUE THREAD

**Issue by supersick123** [AssetKid/raider-release#42]
For example, if I have 5 accounts registered (A, B, C, D and E) in that order...

If I confirm that I want to remove C, C remains but E is removed off the list.

**Comment by AssetKid** [comment]
Hey,

I have not been able to reproduce this on my side. If it is still happening, kindly attach a video/gif showing the issue.

Closing for now.

**Comment by supersick123** [comment]
![newanigif2](https://user-images.githubusercontent.com/63994830/82478361-ad79f400-9a85-11ea-8f0d-38b88326c9cb.gif)

Tried deleting supersickalt1, but supersickalt3 gets removed. Repeated it again and supersickalt2 was removed.

**Comment by AssetKid** [comment]
Fixed in next version.
