### ISSUE TITLE
followers from private other account

### ISSUE THREAD

**Issue by kikieri** [AssetKid/raider-release#44]
Hey,
first of all thanks for this great project, well made!
I logged in with my old account and downloaded from my private old/old one account all pictures.
But I still need all my old/old one followers I followed. Is it stored in the id file? If yes how can I. convert them to names back? 

If not. I fucked up my account from that I downloaded the old old one the login but its still stored in your app. Anyway to get the token/cookie or just to view at my other private account from there to see who I followed back in the days? Its very important for me.....

Any suggestions or ideas?

Thanks in advance!

**Comment by AssetKid** [comment]
Hey,

Raider only downloads media from profiles. Your follower/following list are **not** saved to any file.

> Anyway to get the token/cookie or just to view at my other private account from there to see who I followed back in the days?

Path - `C:\Users\[YOUR USERNAME]\AppData\Roaming\raider-for-instagram`

There should be a file called `prefs` in the folder above. Cookies should be in that file.
