### ISSUE TITLE
bulk subscribe feature

### ISSUE THREAD

**Issue by ayynonwhymouse** [AssetKid/raider-release#46]
Great app, thank you for making it. I'm curious if there is a way to subscribe to all the accounts I follow instantly? It can take quite a while to type them all in by hand.

**Comment by AssetKid** [comment]
There is currently no import feature.

You can edit the accounts file and add the accounts there. It might be easier that way.

More info here - https://github.com/AssetKid/raider-release/issues/3#issuecomment-526864700
