### ISSUE TITLE
[BUG] Showing user folder, sort by newest and suggestions

### ISSUE THREAD

**Issue by logan478** [AssetKid/raider-release#49]
Hello,
after update to 1.5.2 showing user folder option is not longer showing folders and sort by newest option in subscription list is doing nothing, only sort by oldest working. 

Also if i can have suggestion, i would like to have time of updating subscription little bit more detailed, because after 20 hours it is just showing "yesterday" and you dont know when will be for example 24 hours.
Something like reminder or notification of 24 hours also would be great because i already missed stories sometimes.

And last thing i want to ask is if you have some suggestion what to do to not always reach rate limit. I have 650 subscriptions and i must use more accounts because of that. I tried turn off highlights, put mass update sleep timer to 60 seconds, which is a lot because it takes to update 10 hours, i am now using 5 seconds and switching between accounts after reaching limit. About those accounts, is there a way to make that i can stay logged in, but Raider will use only account which have not reached rate limit? Because now when you have many accounts added, if one of them reached already limit, you cant update anything. I am getting those emails from instagram about new logging from unknown device every time after logging in to raider, and they also blocked my one account from logging in.

**Comment by AssetKid** [comment]
The sort bug should be fixed in `v1.5.3`

Kindly open individual issues for the other reports\requests in your post. Generally, an issue should only focus on a single request or report.

Closing this for now.
