### ISSUE TITLE
Allow select name format

### ISSUE THREAD

**Issue by filipivc** [AssetKid/raider-release#5]
Allow select name format to organize: 

- create a folder for each date 
- select datetime format for files (like yyyy-MM-dd HH:mm)

**Comment by AssetKid** [comment]
> create a folder for each date

This sounds like a niche feature that many won't find useful.

> select datetime format for files (like yyyy-MM-dd HH:mm)

I will look into this.

**Comment by AssetKid** [comment]
> select datetime format for files (like yyyy-MM-dd HH:mm)

Starting from `v1.1.0`, you can now change the filename format.
