### ISSUE TITLE
Lost subscription and unable to subscribe/download

### ISSUE THREAD

**Issue by vyronjo** [AssetKid/raider-release#55]
OS: Windows 10

Somehow I lost all the subscription and I tried to subscribe again one by one, but it failed with the prompt "Unable to parse accounts file". Plz help with this and see what's going on?

![image](https://user-images.githubusercontent.com/26548394/91385612-e8997980-e863-11ea-80fc-6ef252ed3f5b.png)

**Comment by AssetKid** [comment]
Sounds like the accounts file got corrupted.

Go to the save folder, rename the `acc` file to something else then try to subscribe to an account.

**Comment by vyronjo** [comment]
> Sounds like the accounts file got corrupted.
> 
> Go to the save folder, rename the `acc` file to something else then try to subscribe to an account.

Thank you, it works.
