### ISSUE TITLE
[BUG]Files Lost When PC Unplugged

### ISSUE THREAD

**Issue by suxxxbang** [AssetKid/raider-release#56]
Recently when I update my subscription, my PC unexpectedly unplugged. When I tried to re-update, it said 'No Account', which is bad cause I got over 400 accounts stored in Raider app. Can it be restored?
![Screenshot_1](https://user-images.githubusercontent.com/68200969/92412990-4c7f4480-f178-11ea-8d06-df57a18adb63.jpg)

**Comment by suxxxbang** [comment]
Additional Note: the acc and _ids files still exist, but they didn't appear like in the first picture
![Screenshot_2](https://user-images.githubusercontent.com/68200969/92413454-5efa7d80-f17a-11ea-87dd-f178fefd054d.jpeg)

**Comment by suxxxbang** [comment]
And this is what happened when I tried to re-download an account
![Screenshot_1](https://user-images.githubusercontent.com/68200969/92413786-e399cb80-f17b-11ea-93a3-f9a726c85b4b.jpg)

**Comment by AssetKid** [comment]
It seems like the `acc` file got corrupted. Open the file in Notepad (or similar) and check if the contents are readable.
