### ISSUE TITLE
[BUG]Can not download all image if the count is up to 2000

### ISSUE THREAD

**Issue by lyscop** [AssetKid/raider-release#57]
I run this program in China, and I use the proxy Shadowsocks, I select the global pattern, it is normal to open Google, Instagram, but there are many the Instagram user images download failed especially the image count is up to 2000. 

These failed downloaded images cannot be downloaded again when I update again.

Is a way to solve the problems. thx

**Comment by AssetKid** [comment]
Duplicate #35
