### ISSUE TITLE
Download accounts with IG IDs and not IG Usernames

### ISSUE THREAD

**Issue by KaunWho** [AssetKid/raider-release#58]
Is there a way download posts based on the IG IDs rather than the Usernames. Every time someone changes their username Raider is unable to find the account and then the posts dont get downloaded. I checked the acc file and we are already making a note of the IG ID (numerical), can the account be updated with it rather than the username? The process for the user stays the same, they enter the Username in Raider, but raider needs to keep updating the data from the User ID. Even if Raider doesnt update the username in its database that would be fine as long as it downloads stuff.

**Comment by AssetKid** [comment]
This is, unfortunately, not possible. The API endpoint used to get a user's info uses the `username`

Example: `https://www.instagram.com/instagram/?__a=1`
