### ISSUE TITLE
Raider using high CPU and Power Resources

### ISSUE THREAD

**Issue by KaunWho** [AssetKid/raider-release#61]
Hey!
Is there a way you can work on making Raider less power hungry. Its extremely power intensive on my Laptop. It makes it practically impossible to work on Chrome/Excel along with Raider on in the background.

![image](https://user-images.githubusercontent.com/58679929/97535930-69026500-19e2-11eb-9ee1-7816f109a975.png)

**Comment by AssetKid** [comment]
Hello,

Are you using the latest version?

**Comment by KaunWho** [comment]
Yup, 1.5.4 is the version

**Comment by AssetKid** [comment]
Is it consistently this high?

**Comment by KaunWho** [comment]
Yes, I tried both updating all account as well as just adding one account at a time to download. The CPU usage is around +25%

**Comment by suxxxbang** [comment]
Perhaps removing smooth scrolling on left tab when we want to update account we subscribed? Just an idea :)
