### ISSUE TITLE
Raider keeps trying to auto-update failed accounts?

### ISSUE THREAD

**Issue by avekifes** [AssetKid/raider-release#63]
I noticed that Raider keeps trying to download failed accounts. Should there be a toggle for that?

**Comment by AssetKid** [comment]
You can enable and disable accounts.

Long press any account to enter edit mode.

![qfLW7WdTga](https://user-images.githubusercontent.com/40426812/98108956-d95f2980-1ead-11eb-9e78-ff19d1942c48.gif)
