### ISSUE TITLE
Need clarification on Raider's downloading order

### ISSUE THREAD

**Issue by avekifes** [AssetKid/raider-release#65]
I thought I read that Raider automatically downloads account based on the time that they were last updated. Is this correct? That doesn't seem to be working, since I'm having a lot of trouble updating the second half of my subscriptions after a lockout.

**Comment by AssetKid** [comment]
> Is this correct?

Yes. Raider auto updates from oldest to newest.

> lockout

See https://github.com/AssetKid/raider-release/issues/66#issuecomment-724824823
