### ISSUE TITLE
Anyone getting their accounts locked?

### ISSUE THREAD

**Issue by avekifes** [AssetKid/raider-release#66]
I switched over from 4K Stogram since it kept locking my accounts, but the same damn thing is happening with Raider despite it not using the Instagram API. Anyone else getting this crap?

**Comment by KaunWho** [comment]
Try updating the timers from settings menu from the top right corner. for me 100, 50, 100 (seconds) works fine. Its more human like so Instagram wont lock you out. Also, once your current lockout ends I would recommend that you wait for a day or two before starting with Raider. Let the old instagram block get some rest. Use your account normally on your PC/Phone and then start with raider. Hope it helps!

**Comment by logan478** [comment]
yeah they dont sending me sms verification code. I dont know what to do, only waiting is option

**Comment by AssetKid** [comment]
As KaunWho said, make sure you increase the `Mass Update Sleep Timer` in the settings drawer.

Also, if you are a heavy Instagram user and still use the same account(s) on Raider, you are likely to be locked out. Instagram detects abnormal traffic (e.g. a user browsing on 2 or more devices concurrently).
