### ISSUE TITLE
Clear cookies? IP ban?

### ISSUE THREAD

**Issue by quietsecret123** [AssetKid/raider-release#72]
I'm not sure if I've been partially IP banned by IG, but here's a new issue I'm experiencing:

When I login to IG like normal, sometimes IG will send me a verification code to my email if they think it's a "suspicious login attempt". This is usually no big deal. I type the code and they let me in.

Recently, for some new accounts of mine, I type the verification code, but I get a reply saying "Sorry, there was a problem. Please try again later". I try to request a new 6-digit code, but it sends me the same one each time, and I get the same error message. This happens both on Raider and the browser I use (Safari; yes, I'm a Mac user. I use Parallels to use Raider).

I figured they didn't like my browser, so I tried logging in through the app, and it worked. I then told IG that the browser/Raider login is me, and it's not suspicious. I tried logging into my browser again and was still rejected. I changed the user agent to simulate my phone browser, and it let me in.

I tried this technique again (ie using a phone browser user agent) for another account that got flagged, but the 6-digit verification code didn't work this time. I got told the same message "Sorry, there was a problem". When I tried a VPN, it sent me a new 6-digit verification code, and I managed to get in. So far, this VPN trick has been working.

What's going on here? Am I IP banned? I can still login to my old accounts with no issues using my "native" IP. It's the new accounts that get flagged when I login with my "native" IP.

I assume Raider keeps cookies. Is there a way to clear those files? Will this fix the problem?

**Comment by AssetKid** [comment]
When you delete an account, all cookies associated with that account are cleared.

The cookies are saved in the `prefs` file.

File location - `%appdata%\raider-for-instagram`
