### ISSUE TITLE
Instagram name change changes folder name.

### ISSUE THREAD

**Issue by AplhaSlayer1964** [AssetKid/raider-release#75]
It would be nice for it to change the folder name of the user when their instagram name changes. Also when a user changes their instagram name sometimes Raider doesn't seem to be able to find them even though they have the same ID.

**Comment by AssetKid** [comment]
Long press an account and an edit button will appear. You can change the username and folder name.

> Raider doesn't seem to be able to find them even though they have the same ID.

A valid username is required to get the initial user info.

**Comment by AplhaSlayer1964** [comment]
Wouldn't it be better if the program did that automatically since it has the user id it can just request the username and check if it's the same. I'm downloading many accounts so I'm unsure if one particular account changes their username slightly.
The account was already added to raidar so it already had gotten the initial user info but it was still showing a 404. adding the new account user name fixed it but I assumed it searched by user id after the first time adding an account and would be able to track the name change.
