### ISSUE TITLE
[BUG] User undefined after first download

### ISSUE THREAD

**Issue by Honsoku** [AssetKid/raider-release#76]
The bug is not quite well defined. The last occurrence was yesterday after manually downloading a single account consisting of 3 images after 5 days of inactivity. It is known to occur after manual downloads. I have not tried automatic downloads. It doesn't trigger after every download. Uninstalling and reinstalling had zero apparent effect once the bug has triggered. Once it triggers, all accounts (including public ones) that I have tried come back the same: "Cannot read property of 'user' of undefined". This looks to last for 24(?) hours from the last download attempt. Every failed attempt seems to reset the clock. This occurs regardless of if there is a user account established for the application to use.

Automatic updates are disabled, so overuse does not seem to be a likely culprit. Due to the apparent 24 hr hold, first thought was this was some new sort of throttling, but something this aggressive would render the API all but useless. It is also puzzling as it doesn't get applied consistently.

Raider Version 1.6.0.0
Windows 10, Version 20H2 (desktop)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36

Error message:
![Raider Bug](https://user-images.githubusercontent.com/77935460/105640023-4cd75e00-5e41-11eb-9c53-b3b13acf7749.png)

Recent download history:
![Raider Bug 2](https://user-images.githubusercontent.com/77935460/105641160-3c76b180-5e48-11eb-8e65-a645c115ac5a.png)

**Comment by AssetKid** [comment]
Duplicate #53
