### ISSUE TITLE
Have account file seperate from download location

### ISSUE THREAD

**Issue by AplhaSlayer1964** [AssetKid/raider-release#77]
This would be useful because I'm running this program twice one through a vpn and would like to have everything saved to the same location but can't because each instance is downloading half so they need their own account files. Doing it this way to stop instagram from flagging my account as compromised because adding two accounts on one instance doesn't seem to stop it from happening.

**Comment by AssetKid** [comment]
This sounds like a very niche request. You can easily make a script that moves files from one folder to another.

Windows has a very powerful command-line utility called [Robocopy](https://en.wikipedia.org/wiki/Robocopy). There is also a utility called Task Scheduler that might also be helpful. Here are some links to get you started:

- [https://adamtheautomator.com/robocopy-the-ultimate/](https://adamtheautomator.com/robocopy-the-ultimate/)
- [https://www.laptopmag.com/articles/automatically-move-files-one-folder-another-windows-10](https://www.laptopmag.com/articles/automatically-move-files-one-folder-another-windows-10)

Create a few dummy folders to test you script.
