### ISSUE TITLE
Add interval between each account request to avoid rate limiting

### ISSUE THREAD

**Issue by avekifes** [AssetKid/raider-release#9]
I was asked to open new requests for two of the suggestions I had made in a previous thread (https://github.com/AssetKid/raider-release/issues/3). Here's the first of them:

_Refine the "update all" function so Raider cycles through all subscribed accounts indefinitely (so no Stories are missed), but have it update only one account at a time (with a short interval between each) so rate limiting isn't triggered._

I believe Raider's "Auto Update Interval" takes care of the first portion, but can you add a way for users to set an interval between each account request? I think this is the key to avoiding rate limiting.

**Comment by AssetKid** [comment]
Hello,

Are you using the latest version `v1.3.0`? Rate limit handling was greatly improved in the last 2 versions.

**Comment by avekifes** [comment]
I'm afraid to try it. The following feature update (from v 1.2.0) suggests that rate limiting is still a very real possibility.

_Better handling of 429 Too Many Request error. The app will now stop downloads when Instagram starts rate limiting requests._

That would mean a 24-hour ban for my main account.

I'm currently using 4K Stogram to download Instagram content, and I've never run into rate limiting so long as I update each account manually, one at a time, with a generous delay between each. I would switch to Raider if it could do this automatically.

**Comment by avekifes** [comment]
Okay, I just tried a mass update with a 60-second download timeout and maximum of 50 posts. Got rate limited after updating 227 accounts.

**Comment by AssetKid** [comment]
Was your account banned?

**Comment by avekifes** [comment]
No, but I wasn't able to access anything until this morning.

**Comment by AssetKid** [comment]
Added in [`v1.5.0`](https://github.com/AssetKid/raider-release/releases/tag/v1.5.0) under `General > Mass Update Sleep Timer`

Try it out.

**Comment by avekifes** [comment]
This doesn't seem to be working. I set the option to 30 seconds but am not seeing any kind of delay between accounts.

**Comment by AssetKid** [comment]
Have you tried with a larger number like 300 (5 mins) during your testing? By the time the application is done downloading files for an account, 30 seconds might have already elapsed.

Move your mouse to the bottom right of the application window. A light red `bug` icon should appear.

Click on it to open the log window then check the timestamps between profile requests.

**Comment by avekifes** [comment]
Ah, so the delay/interval begins not when the last download was completed, but when an account update is first started? I'll try it again later and report back.

**Comment by avekifes** [comment]
I'm happy to report that the feature appears to be working; I'm two hours into a mass update and haven't been banned yet.

Out of curiosity, could the sleep timer be tweaked so the interval begins after an account _finishes_ updating instead of when an account _begins_ updating, so the periods of inactivity between updates are consistent?

**Comment by AssetKid** [comment]
> after an account finishes updating

Do you mean after the images & videos are downloaded?

**Comment by avekifes** [comment]
Yes. If I'm understanding things correctly, the sleep timer currently behaves like this:

> [Sleep timer set to 30 seconds]: Profile 1 takes 20 seconds to update. Raider begins downloading/updating Profile 2 after 10 seconds.
> 
> [Sleep timer set to 30 seconds]: Profile 1 takes 60 seconds to update. Raider immediately moves on to Profile 2 with no delay.

Ideally, the timer should begin only after an update is complete:

> [Sleep timer set to 30 seconds]: Profile 1 takes 20 seconds to update. Raider begins downloading/updating Profile 2 after 30 seconds.
> 
> [Sleep timer set to 30 seconds]: Profile 1 takes 60 seconds to update. Raider begins downloading/updating Profile 2 after 30 seconds.

**Comment by AssetKid** [comment]
When the application is downloading images & videos, no API requests are taking place. The app collects all the links requested via API Requests then starts downloading them after.

Instagram, at the moment, only rate limits API requests, not media downloads.

**Comment by avekifes** [comment]
So with the way the sleep timer works now, the interval between API requests are effectively identical? I guess we can leave that alone, then.

**Comment by AssetKid** [comment]
Yeah. There is no need to change it for now since it is working just fine. I have been testing the feature for a few days now and I have not seen a single `429` error.

**Comment by avekifes** [comment]
Speaking of API requests, is the following information still valid?

> A single profile page query returns 50 posts. The stories query returns 100 entries.
> 
> If you set Mass Update Max Posts to 200 and also fetch stories, those will be 5 total API queries. If you have a lot of accounts, maybe reduce the Mass Update Max Posts to 50 or 100.

The implication is that there is a minimum of three API requests that must be made for a complete update (images, video, stories, highlights), correct? (I'm assuming that "highlights" requires an additional API request.)

**Comment by AssetKid** [comment]
* Get User Info - 1 API call
* Fetch 50 posts (images & videos) from a user's feed (`Mass Update Max Posts` set to 50 or below) - 1 API call
* Fetch all stories - 1 API call

Highlights are slightly complicated.

* Fetch the IDs for all users highlights - 1 API call

Unlike stories, we can't fetch all highlights at once. The maximum during my testing was 10 highlight reels per request (See #4 for more info)

* 10 highlight reels - 1 API call
* 13 highlight reels  - 2 API calls

I do disable highlights and only get them maybe twice per week.

**Comment by supersick123** [comment]
Just to clarify, is a grouping of highlights (e.g. "Food" or "NYC" or "Gym" or "Beach"), a "highlight reel"? Or is each individual post in someone's highlights = 1 API call?
